---
version: '3.6'
services:
  db:
    container_name: szpitale-db
    image: postgres:10.4-alpine

  api:
    container_name: szpitale-api
    build: .
    command: bundle exec rails server -b 0.0.0.0 -p 3000 --no-dev-caching
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    tmpfs:
      - /app/tmp
    tty: true
    stdin_open: true
    environment:
      RAILS_LOG_TO_STDOUT: '1'
      PORT: '3000'
    depends_on:
      - db
    links:
      - db
